default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: <%= Integer(ENV.fetch('DB_POOL', 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: <%= Integer(ENV.fetch('DB_TIMEOUT', 5000)) %>

development:
  <<: *default
  database: <%= Rails.application.name %>_development

test:
  <<: *default
  database: <%= Rails.application.name %>_test

deploy: &deploy
  <<: *default
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

production: *deploy
staging: *deploy
