#= require active_admin/base
#= require best_in_place
#= require jquery.purr

BestInPlaceEditor.defaults.purrErrorContainer = '<ul class=\'bip-flash-error\'></ul>'
jQuery(document).on 'best_in_place:error', (event, request, error) ->
  'use strict'
  # Display all error messages from server side validation
  jQuery.each jQuery.parseJSON(request.responseText), (index, value) ->
    if index == 'errors'
      container = jQuery(BestInPlaceEditor.defaults.purrErrorContainer)
      jQuery.each value, (attr, errors) ->
        jQuery.each errors, (index, error) ->
          container.append "<li>#{error}</li>"

      # container.purr(isSticky: true)
      $(event.target).after(container)

# ---
# generated by js2coffee 2.2.0
$(document).ready ->
  jQuery(".best_in_place").best_in_place()
